@startuml
'https://plantuml.com/class-diagram

package model {


    class WortPaar {
        - bildURL : String
        - wort : String

        + WortPaar(antwort : String, bildURL: String)
        + checkAntwort(antwort : String) : boolean

        + getWort() : String
        + getBildURL() : String
    }

    class WortTrainer {
        - wortListe : ArrayList<WortPaar>
        - statistikManager : StatistikManager
        - aktuellesIndex : int

        + nextWort() : void
        + checkAntwort(antwort : String) : boolean

        + setWortListe(wortListe : ArrayList<WortPaar>) : void
        + setStatistik(statistikManager : StatistikManager) : void

        + getAktuellesWort() : WortPaar
    }

    class StatistikManager {
        - insgesamt : int
        - anzahlRichtig : int
        - anzahlFalsch : int

        + addRichtig() : void
        + addFalsch() : void
        + toString() : String

        + getInsgesamt() : int
        + getAnzahlRichtig() : int
        + getAnzahlFalsch() : int

        + setInsgesamt(insgesamt : int) : void
        + setAnzahlFalsch(anzahlFalsch : int) : void
        + setAnzahlRichtig(anzahlRichtig : int) : void
    }
}


package view {
    class ViewClass {
    }
}

package controller {
    class ControllClass {
    }
}




WortTrainer "1" -> "0..*" WortPaar
WortTrainer -> "1" StatistikManager

@enduml