@startuml
'https://plantuml.com/class-diagram

package model {


    class WortPaar {
        - bildURL : String
        - wort : String
        + checkAntwort() : boolean
    }


    class WortTrainer {
        - wortListe : ArrayList<WortPaar>
        - statistikManager : StatistikManager
        - aktuellesIndex : int
        + randomIndex() : int
    }

    class StatistikManager {
        - anzahlRichtig : int
        - anzahlFalsch : int
        + addRichtig() : void
    }
}


package view {
    class ViewClass {
    }
}

package controller {
    class ControllClass {
    }
}




WortTrainer "1" -- "0..*" WortPaar
WortTrainer -- "1" StatistikManager

@enduml